project_id = "nnytrkgsjajsecotasqv"

[functions.webhook-handler]
verify_jwt = false

[functions.get-medico-dados]
verify_jwt = false

[functions.processar-aprovacao]
verify_jwt = false

[functions.send-email-notification]
verify_jwt = false

[functions.send-notification-gestores]
verify_jwt = false

[functions.test-whatsapp-message]
verify_jwt = false
